# Generated by Django 5.0.6 on 2024-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_genre_listeninghistory_topgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topgenre',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
