# Generated by Django 5.0.6 on 2024-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_topgenre_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttrack',
            name='artist_image',
            field=models.URLField(blank=True),
        ),
    ]
