# Generated by Django 5.0.6 on 2024-05-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_recenttrack_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topartist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topartist',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='topartist',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
