# Generated by Django 5.0.6 on 2024-05-28 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_topartist_description_topartist_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptrack',
            name='artist_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='toptrack',
            name='played_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 1, 24, 4, 705370, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
