# Generated by Django 5.0.6 on 2024-05-28 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_toptrack_artist_image_toptrack_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeninghistory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='track',
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='artist',
            field=models.CharField(default='Exo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='artist_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='name',
            field=models.CharField(default='Exo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='played_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 1, 47, 13, 407983, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 28, 1, 47, 24, 423251, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
