# Generated by Django 5.0.6 on 2024-05-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_remove_listeninghistory_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='artist_image',
            field=models.URLField(blank=True, max_length=199),
        ),
    ]
