# Generated by Django 5.0.6 on 2024-05-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_alter_listeninghistory_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='artist_image',
            field=models.URLField(blank=True),
        ),
    ]
