# Generated by Django 5.0.6 on 2024-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_spotifytoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
        migrations.RemoveField(
            model_name='toptrack',
            name='played_at',
        ),
    ]
